from __future__ import annotations
"""
Seed script for incentive programs.

Populates the incentive_programs table with comprehensive data from incentive-research.md.
Covers federal, state (15 states), manufacturer, utility, and affinity incentives
plus stacking/mutual-exclusion rules.

Usage:
    python -m scripts.seed_incentives          # default DB URL from config
    DATABASE_URL=postgres://... python -m scripts.seed_incentives
"""

import asyncio
import json
import os
import uuid
from datetime import datetime, timezone

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql+asyncpg://postgres:postgres@localhost:5432/incentive_drive",
)

# ---------------------------------------------------------------------------
# Deterministic UUIDs (namespace-based) so that stacking rules can cross-
# reference other programs and re-runs are idempotent.
# ---------------------------------------------------------------------------
NS = uuid.UUID("a1b2c3d4-e5f6-7890-abcd-ef1234567890")


def _id(slug: str) -> uuid.UUID:
    return uuid.uuid5(NS, slug)


NOW = datetime.now(timezone.utc)

# ---------------------------------------------------------------------------
# Helper to build an incentive dict matching the incentive_programs table
# ---------------------------------------------------------------------------

def _program(
    slug: str,
    *,
    name: str,
    type: str,
    source_authority: str,
    geographic_scope: str,
    eligible_states: list[str] | None = None,
    eligible_zips: list[str] | None = None,
    vehicle_criteria: dict | None = None,
    buyer_criteria: dict | None = None,
    incentive_value_type: str,
    incentive_amount: float | None = None,
    incentive_max_amount: float | None = None,
    incentive_percentage: float | None = None,
    start_date: str,
    end_date: str | None = None,
    application_deadline: str | None = None,
    funding_status: str = "open",
    claim_mechanism: str,
    source_url: str,
    confidence_score: float = 0.8,
    is_active: bool = True,
) -> dict:
    return {
        "id": _id(slug),
        "name": name,
        "type": type,
        "source_authority": source_authority,
        "geographic_scope": geographic_scope,
        "eligible_states": eligible_states or [],
        "eligible_zips": eligible_zips or [],
        "vehicle_criteria": vehicle_criteria or {},
        "buyer_criteria": buyer_criteria or {},
        "incentive_value_type": incentive_value_type,
        "incentive_amount": incentive_amount,
        "incentive_max_amount": incentive_max_amount,
        "incentive_percentage": incentive_percentage,
        "stackable_with": [],
        "mutually_exclusive_with": [],
        "start_date": datetime.fromisoformat(start_date).replace(tzinfo=timezone.utc),
        "end_date": datetime.fromisoformat(end_date).replace(tzinfo=timezone.utc) if end_date else None,
        "application_deadline": datetime.fromisoformat(application_deadline).replace(tzinfo=timezone.utc) if application_deadline else None,
        "funding_status": funding_status,
        "claim_mechanism": claim_mechanism,
        "last_verified": NOW,
        "source_url": source_url,
        "confidence_score": confidence_score,
        "is_active": is_active,
        "created_at": NOW,
        "updated_at": NOW,
    }


# ============================================================================
# FEDERAL INCENTIVES
# ============================================================================

FEDERAL = [
    # 30D - TERMINATED
    _program(
        "fed-30d",
        name="Section 30D New Clean Vehicle Credit",
        type="federal",
        source_authority="IRS",
        geographic_scope="national",
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV", "FCEV"],
            "new_or_used": "new",
            "msrp_cap_sedan": 55000,
            "msrp_cap_suv": 80000,
            "assembly": "north_america",
        },
        buyer_criteria={
            "income_type": "MAGI",
            "income_limits": {
                "single": 150000,
                "head_of_household": 225000,
                "married_filing_jointly": 300000,
            },
        },
        incentive_value_type="tax_credit",
        incentive_amount=7500,
        incentive_max_amount=7500,
        start_date="2023-01-01",
        end_date="2025-09-30",
        funding_status="depleted",
        claim_mechanism="tax_return",
        source_url="https://www.irs.gov/credits-deductions/credits-for-new-clean-vehicles-purchased-in-2023-or-after",
        confidence_score=1.0,
        is_active=False,
    ),
    # 25E - TERMINATED
    _program(
        "fed-25e",
        name="Section 25E Used Clean Vehicle Credit",
        type="federal",
        source_authority="IRS",
        geographic_scope="national",
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV", "FCEV"],
            "new_or_used": "used",
            "price_cap": 25000,
        },
        buyer_criteria={
            "income_type": "MAGI",
            "income_limits": {
                "single": 75000,
                "head_of_household": 112500,
                "married_filing_jointly": 150000,
            },
        },
        incentive_value_type="tax_credit",
        incentive_percentage=30,
        incentive_max_amount=4000,
        start_date="2023-01-01",
        end_date="2025-09-30",
        funding_status="depleted",
        claim_mechanism="tax_return",
        source_url="https://www.irs.gov/credits-deductions/used-clean-vehicle-credit",
        confidence_score=1.0,
        is_active=False,
    ),
    # 45W - TERMINATED
    _program(
        "fed-45w",
        name="Section 45W Commercial Clean Vehicle Credit",
        type="federal",
        source_authority="IRS",
        geographic_scope="national",
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV", "FCEV"],
            "commercial_use": True,
        },
        buyer_criteria={"business_use": True},
        incentive_value_type="tax_credit",
        incentive_amount=7500,
        incentive_max_amount=40000,
        incentive_percentage=30,
        start_date="2023-01-01",
        end_date="2025-09-30",
        funding_status="depleted",
        claim_mechanism="tax_return",
        source_url="https://www.irs.gov/credits-deductions/commercial-clean-vehicle-credit",
        confidence_score=1.0,
        is_active=False,
    ),
    # 30C - STILL ACTIVE
    _program(
        "fed-30c",
        name="Section 30C EV Charger Installation Credit",
        type="federal",
        source_authority="IRS",
        geographic_scope="national",
        vehicle_criteria={"category": "charger_installation"},
        buyer_criteria={
            "location_requirement": "low_income_or_rural_census_tract",
            "individual_max": 1000,
            "business_max": 100000,
        },
        incentive_value_type="tax_credit",
        incentive_percentage=30,
        incentive_max_amount=1000,
        start_date="2023-01-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="tax_return",
        source_url="https://www.irs.gov/credits-deductions/alternative-fuel-vehicle-refueling-property-credit",
        confidence_score=1.0,
        is_active=True,
    ),
]

# ============================================================================
# STATE INCENTIVES (15 states)
# ============================================================================

STATE = [
    # --- California ---
    _program(
        "ca-cc4a",
        name="California Clean Cars 4 All (CC4A)",
        type="state",
        source_authority="California CARB",
        geographic_scope="state",
        eligible_states=["CA"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV", "FCEV"],
            "new_or_used": "both",
        },
        buyer_criteria={
            "income_type": "FPL_percentage",
            "income_max_pct_fpl": 300,
            "scrap_required": True,
            "participating_air_district": True,
        },
        incentive_value_type="fixed",
        incentive_amount=12000,
        incentive_max_amount=14000,
        start_date="2020-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://ww2.arb.ca.gov/our-work/programs/clean-cars-4-all/about",
    ),
    _program(
        "ca-dcap",
        name="California Driving Clean Assistance Program (DCAP)",
        type="state",
        source_authority="California CARB",
        geographic_scope="state",
        eligible_states=["CA"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV", "FCEV"],
            "new_or_used": "both",
        },
        buyer_criteria={
            "income_type": "FPL_percentage",
            "income_max_pct_fpl": 300,
        },
        incentive_value_type="fixed",
        incentive_amount=5000,
        incentive_max_amount=5000,
        start_date="2020-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://ww2.arb.ca.gov/our-work/programs/clean-cars-4-all/about",
    ),
    # --- Colorado ---
    _program(
        "co-ev-tax-credit",
        name="Colorado State EV Tax Credit (2026)",
        type="state",
        source_authority="Colorado Energy Office",
        geographic_scope="state",
        eligible_states=["CO"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV"],
            "new_or_used": "new",
            "msrp_cap": 80000,
        },
        buyer_criteria={},
        incentive_value_type="tax_credit",
        incentive_amount=750,
        incentive_max_amount=3250,
        start_date="2026-01-01",
        end_date="2026-12-31",
        funding_status="open",
        claim_mechanism="tax_return",
        source_url="https://energyoffice.colorado.gov/transportation/grants-incentives/electric-vehicle-tax-credits",
    ),
    _program(
        "co-vxc",
        name="Colorado Vehicle Exchange Colorado (VXC)",
        type="state",
        source_authority="Colorado Energy Office",
        geographic_scope="state",
        eligible_states=["CO"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV"],
            "new_or_used": "both",
        },
        buyer_criteria={
            "income_qualified": True,
            "trade_in_required": True,
        },
        incentive_value_type="fixed",
        incentive_amount=9000,
        incentive_max_amount=9000,
        start_date="2024-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://energyoffice.colorado.gov/transportation/grants-incentives/electric-vehicle-tax-credits",
    ),
    # --- New York ---
    _program(
        "ny-drive-clean",
        name="New York Drive Clean Rebate (NYSERDA)",
        type="state",
        source_authority="NYSERDA",
        geographic_scope="state",
        eligible_states=["NY"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV"],
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=2000,
        incentive_max_amount=2000,
        start_date="2023-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.nyserda.ny.gov/All-Programs/Drive-Clean-Rebate-For-Electric-Cars-Program",
    ),
    # --- New Jersey ---
    _program(
        "nj-charge-up",
        name="New Jersey Charge Up NJ",
        type="state",
        source_authority="NJ Board of Public Utilities",
        geographic_scope="state",
        eligible_states=["NJ"],
        vehicle_criteria={
            "fuel_types": ["BEV"],
            "new_or_used": "new",
        },
        buyer_criteria={
            "base_rebate": 1500,
            "income_qualified_adder": 2500,
        },
        incentive_value_type="fixed",
        incentive_amount=1500,
        incentive_max_amount=4000,
        start_date="2023-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://chargeup.njcleanenergy.com/",
    ),
    # --- Massachusetts ---
    _program(
        "ma-mor-ev",
        name="Massachusetts MOR-EV Rebate",
        type="state",
        source_authority="Massachusetts DEP / MOR-EV",
        geographic_scope="state",
        eligible_states=["MA"],
        vehicle_criteria={
            "fuel_types": ["BEV"],
            "new_or_used": "new",
            "msrp_cap": 55000,
        },
        buyer_criteria={
            "standard_rebate": 3500,
            "income_qualified_adder": 1500,
            "trade_in_bonus": 1000,
        },
        incentive_value_type="fixed",
        incentive_amount=3500,
        incentive_max_amount=6000,
        start_date="2023-01-01",
        funding_status="open",
        claim_mechanism="post_purchase_rebate",
        source_url="https://mor-ev.org/",
    ),
    # --- Connecticut ---
    _program(
        "ct-cheapr-standard",
        name="Connecticut CHEAPR Standard Rebate",
        type="state",
        source_authority="Connecticut DEEP",
        geographic_scope="state",
        eligible_states=["CT"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV"],
            "new_or_used": "new",
            "msrp_cap": 50000,
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=1000,
        start_date="2025-10-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://portal.ct.gov/DEEP/Air/Mobile-Sources/CHEAPR/CHEAPR---Home",
    ),
    _program(
        "ct-cheapr-plus",
        name="Connecticut CHEAPR Rebate+ (Income-Qualified)",
        type="state",
        source_authority="Connecticut DEEP",
        geographic_scope="state",
        eligible_states=["CT"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV"],
            "new_or_used": "both",
            "msrp_cap": 50000,
        },
        buyer_criteria={"income_qualified": True},
        incentive_value_type="fixed",
        incentive_amount=4000,
        incentive_max_amount=5000,
        start_date="2025-10-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://portal.ct.gov/DEEP/Air/Mobile-Sources/CHEAPR/CHEAPR---Home",
    ),
    # --- Illinois ---
    _program(
        "il-ceja",
        name="Illinois EV Rebate (CEJA)",
        type="state",
        source_authority="Illinois EPA",
        geographic_scope="state",
        eligible_states=["IL"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV"],
            "new_or_used": "new",
            "price_cap": 80000,
        },
        buyer_criteria={
            "income_type": "FPL_percentage",
            "income_max_pct_fpl": 500,
            "low_income_adder": 2000,
        },
        incentive_value_type="fixed",
        incentive_amount=2000,
        incentive_max_amount=4000,
        start_date="2024-01-01",
        application_deadline="2026-05-31",
        funding_status="open",
        claim_mechanism="post_purchase_rebate",
        source_url="https://epa.illinois.gov/topics/ceja/electric-vehicle-rebates.html",
    ),
    # --- Oregon (SUSPENDED) ---
    _program(
        "or-ev-rebate",
        name="Oregon Clean Vehicle Rebate",
        type="state",
        source_authority="Oregon DEQ",
        geographic_scope="state",
        eligible_states=["OR"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV"],
            "new_or_used": "both",
        },
        buyer_criteria={"income_qualified": True},
        incentive_value_type="fixed",
        incentive_amount=7500,
        incentive_max_amount=7500,
        start_date="2019-01-01",
        funding_status="suspended",
        claim_mechanism="post_purchase_rebate",
        source_url="https://www.oregon.gov/deq/aq/programs/pages/zev-rebate.aspx",
        is_active=False,
    ),
    # --- Maryland (DEPLETED) ---
    _program(
        "md-excise-tax-credit",
        name="Maryland Excise Tax Credit",
        type="state",
        source_authority="Maryland MVA",
        geographic_scope="state",
        eligible_states=["MD"],
        vehicle_criteria={
            "fuel_types": ["BEV"],
            "new_or_used": "new",
            "price_cap": 50000,
        },
        buyer_criteria={},
        incentive_value_type="tax_credit",
        incentive_amount=3000,
        incentive_max_amount=3000,
        start_date="2020-01-01",
        funding_status="depleted",
        claim_mechanism="point_of_sale",
        source_url="https://mva.maryland.gov/vehicles/Pages/27300-71T.aspx",
        is_active=False,
    ),
    # --- Maine ---
    _program(
        "me-ev-rebate",
        name="Maine EV Rebate",
        type="state",
        source_authority="Efficiency Maine",
        geographic_scope="state",
        eligible_states=["ME"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV"],
            "new_or_used": "both",
        },
        buyer_criteria={"income_qualified": True},
        incentive_value_type="fixed",
        incentive_amount=2000,
        incentive_max_amount=7500,
        start_date="2023-01-01",
        funding_status="suspended",
        claim_mechanism="post_purchase_rebate",
        source_url="https://www.efficiencymaine.com/ev/",
        confidence_score=0.7,
    ),
    # --- Vermont ---
    _program(
        "vt-ev-incentive",
        name="Vermont EV Incentive",
        type="state",
        source_authority="Vermont Agency of Transportation",
        geographic_scope="state",
        eligible_states=["VT"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV"],
            "new_or_used": "both",
        },
        buyer_criteria={"income_qualified": True},
        incentive_value_type="fixed",
        incentive_amount=3000,
        incentive_max_amount=3000,
        start_date="2023-01-01",
        funding_status="depleted",
        claim_mechanism="post_purchase_rebate",
        source_url="https://vtrans.vermont.gov/",
        confidence_score=0.7,
        is_active=False,
    ),
    # --- Rhode Island ---
    _program(
        "ri-ev-rebate",
        name="Rhode Island EV Purchase Incentive",
        type="state",
        source_authority="Rhode Island OER",
        geographic_scope="state",
        eligible_states=["RI"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV"],
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=1500,
        incentive_max_amount=1500,
        start_date="2023-01-01",
        funding_status="open",
        claim_mechanism="post_purchase_rebate",
        source_url="https://drive.ri.gov/",
        confidence_score=0.7,
    ),
    # --- Pennsylvania ---
    _program(
        "pa-ev-rebate",
        name="Pennsylvania EV Rebate",
        type="state",
        source_authority="Pennsylvania DEP",
        geographic_scope="state",
        eligible_states=["PA"],
        vehicle_criteria={
            "fuel_types": ["BEV", "PHEV"],
            "new_or_used": "both",
            "price_cap": 45000,
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=3000,
        incentive_max_amount=3000,
        start_date="2023-01-01",
        funding_status="open",
        claim_mechanism="post_purchase_rebate",
        source_url="https://www.dep.pa.gov/",
        confidence_score=0.7,
    ),
]

# ============================================================================
# MANUFACTURER INCENTIVES
# ============================================================================

MANUFACTURER = [
    # ===== HYUNDAI =====
    # --- IONIQ 5: Dealer Choice Bonus Cash (HMF financing required) ---
    _program(
        "mfr-hyundai-ioniq5-dealer-choice",
        name="Hyundai IONIQ 5 Dealer Choice Bonus Cash (up to $10,000)",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["IONIQ 5"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={
            "captive_financing": "Hyundai Motor Finance",
            "note": "Requires HMF financing; rate may be 5.99-6.99% APR. Dealer sets final rate.",
        },
        incentive_value_type="fixed",
        incentive_amount=10000,
        incentive_max_amount=10000,
        start_date="2026-02-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.carsdirect.com/deals-articles/2026-hyundai-ioniq-5-10-000-rebate-isn-t-what-you-think",
        confidence_score=0.85,
    ),
    # --- IONIQ 5/9: 0% APR 72 months + $5,000 Low APR Bonus Cash ---
    _program(
        "mfr-hyundai-ioniq5-0apr-bonus",
        name="Hyundai IONIQ 5 0% APR 72 months + $5,000 Bonus Cash",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["IONIQ 5"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={
            "captive_financing": "Hyundai Motor Finance",
            "credit_tier": "top_tier",
        },
        incentive_value_type="fixed",
        incentive_amount=5000,
        incentive_max_amount=5000,
        start_date="2026-02-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.hyundaiusa.com/us/en/offers",
        confidence_score=0.9,
    ),
    _program(
        "mfr-hyundai-ioniq5-0apr",
        name="Hyundai IONIQ 5 0% APR for 72 months",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["IONIQ 5"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={
            "captive_financing": "Hyundai Motor Finance",
            "credit_tier": "top_tier",
        },
        incentive_value_type="rate_reduction",
        incentive_percentage=0,
        start_date="2026-02-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.hyundaiusa.com/us/en/offers",
        confidence_score=0.9,
    ),
    # --- IONIQ 9: $5,000 rebate + 0% APR 72 months ---
    _program(
        "mfr-hyundai-ioniq9-bonus",
        name="Hyundai IONIQ 9 $5,000 Bonus Cash",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["IONIQ 9"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={"captive_financing": "Hyundai Motor Finance"},
        incentive_value_type="fixed",
        incentive_amount=5000,
        incentive_max_amount=5000,
        start_date="2026-02-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.carsdirect.com/deals-articles/2026-hyundai-ioniq-9-already-has-a-5-000-rebate",
        confidence_score=0.85,
    ),
    _program(
        "mfr-hyundai-ioniq9-0apr",
        name="Hyundai IONIQ 9 0% APR for 72 months",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["IONIQ 9"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={
            "captive_financing": "Hyundai Motor Finance",
            "credit_tier": "top_tier",
        },
        incentive_value_type="rate_reduction",
        incentive_percentage=0,
        start_date="2026-02-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.hyundaiusa.com/us/en/offers",
        confidence_score=0.9,
    ),
    # --- IONIQ 6: $5,000 price cut ---
    _program(
        "mfr-hyundai-ioniq6-bonus",
        name="Hyundai IONIQ 6 $5,000 Bonus Cash",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["IONIQ 6"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={"captive_financing": "Hyundai Motor Finance"},
        incentive_value_type="fixed",
        incentive_amount=5000,
        incentive_max_amount=5000,
        start_date="2026-02-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.carsdirect.com/deals-articles/hyundai-ioniq-6-gets-5-000-price-cut",
        confidence_score=0.85,
    ),
    # --- Elantra: $750 Customer Cash + Lease Cash ---
    _program(
        "mfr-hyundai-elantra-cash",
        name="Hyundai Elantra $750 Customer Cash",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["Elantra"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=750,
        incentive_max_amount=750,
        start_date="2026-01-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.hyundaiusa.com/us/en/offers",
        confidence_score=0.85,
    ),
    _program(
        "mfr-hyundai-elantra-lease-cash",
        name="Hyundai Elantra $1,750 Lease Cash",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["Elantra"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={"lease_only": True},
        incentive_value_type="fixed",
        incentive_amount=1750,
        incentive_max_amount=1750,
        start_date="2026-01-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.hyundaiusa.com/us/en/offers",
        confidence_score=0.85,
    ),
    # --- Hyundai Competitive Owner Coupon (conquest) ---
    _program(
        "mfr-hyundai-competitive-owner",
        name="Hyundai Competitive Owner Coupon",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "new_or_used": "new",
        },
        buyer_criteria={
            "conquest_type": "switching_from_competitor",
            "proof_required": "registration_of_non_hyundai_non_kia",
            "note": "Must own/lease a non-Hyundai, non-Kia, non-Genesis vehicle",
        },
        incentive_value_type="fixed",
        incentive_amount=500,
        incentive_max_amount=2500,
        start_date="2026-01-01",
        end_date="2026-12-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.carsdirect.com/deals-articles/hyundai-competitive-owner-coupon-explained",
        confidence_score=0.8,
    ),
    # --- Hyundai Tucson 0% APR ---
    _program(
        "mfr-hyundai-tucson-0apr",
        name="Hyundai Tucson 0% APR for 60 months",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["Tucson"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={"captive_financing": "Hyundai Motor Finance"},
        incentive_value_type="rate_reduction",
        incentive_percentage=0,
        start_date="2025-12-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.hyundaiusa.com/us/en/offers",
        confidence_score=0.85,
    ),
    # --- Hyundai Santa Fe 0% APR ---
    _program(
        "mfr-hyundai-santafe-0apr",
        name="Hyundai Santa Fe 0% APR for 60 months",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["Santa Fe"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={"captive_financing": "Hyundai Motor Finance"},
        incentive_value_type="rate_reduction",
        incentive_percentage=0,
        start_date="2025-12-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.hyundaiusa.com/us/en/offers",
        confidence_score=0.85,
    ),
    # --- Hyundai Elantra 0.99% APR ---
    _program(
        "mfr-hyundai-elantra-apr",
        name="Hyundai Elantra 0.99% APR for 60 months",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["Elantra"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={"captive_financing": "Hyundai Motor Finance"},
        incentive_value_type="rate_reduction",
        incentive_percentage=0.99,
        start_date="2026-01-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.hyundaiusa.com/us/en/offers",
        confidence_score=0.85,
    ),
    # --- Hyundai Sonata 0.99% APR ---
    _program(
        "mfr-hyundai-sonata-apr",
        name="Hyundai Sonata 0.99% APR for 60 months",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["Sonata"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={"captive_financing": "Hyundai Motor Finance"},
        incentive_value_type="rate_reduction",
        incentive_percentage=0.99,
        start_date="2026-01-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.hyundaiusa.com/us/en/offers",
        confidence_score=0.85,
    ),
    # ===== TOYOTA =====
    _program(
        "mfr-toyota-bz-cash",
        name="Toyota bZ Cash Back (up to $7,000)",
        type="manufacturer",
        source_authority="Toyota USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Toyota",
            "models": ["bZ"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=7000,
        incentive_max_amount=7000,
        start_date="2026-01-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.kbb.com/toyota/deals-incentives/",
        confidence_score=0.8,
    ),
    # ===== CHEVROLET / GM =====
    _program(
        "mfr-chevy-silverado-supplier",
        name="Chevrolet Silverado 1500 Supplier Pricing + Cash Allowance",
        type="manufacturer",
        source_authority="General Motors",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Chevrolet",
            "models": ["Silverado"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=7360,
        incentive_max_amount=7360,
        start_date="2026-03-03",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.carsdirect.com/deals-articles/best-new-car-deals",
        confidence_score=0.8,
    ),
    _program(
        "mfr-gm-costco-bonus",
        name="GM Costco Member Bonus ($1,000-$1,250)",
        type="manufacturer",
        source_authority="General Motors",
        geographic_scope="national",
        vehicle_criteria={
            "make": ["Chevrolet", "GMC", "Buick", "Cadillac"],
            "new_or_used": "new",
        },
        buyer_criteria={
            "affinity_group": "costco_member",
            "note": "$1,250 for Executive Members, $1,000 for Gold Star",
        },
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=1250,
        start_date="2026-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.chevrolet.com/current-offers",
        confidence_score=0.8,
    ),
    # ===== HYUNDAI LOYALTY =====
    _program(
        "mfr-hyundai-valued-owner",
        name="Hyundai Valued Owner Coupon (Loyalty)",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={"make": "Hyundai", "new_or_used": "new"},
        buyer_criteria={
            "loyalty_type": "same_brand",
            "proof_required": "registration_of_hyundai",
            "note": "Cannot combine with Competitive Owner Coupon",
        },
        incentive_value_type="fixed",
        incentive_amount=500,
        incentive_max_amount=2500,
        start_date="2026-01-01",
        end_date="2026-12-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.patrickhyundai.com/customer-loyalty-incentives-and-conquest-rebates/",
        confidence_score=0.8,
    ),
    _program(
        "mfr-hyundai-tucson-cash",
        name="Hyundai Tucson $2,000 Customer Cash",
        type="manufacturer",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Hyundai",
            "models": ["Tucson"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=2000,
        incentive_max_amount=2000,
        start_date="2026-01-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.kbb.com/hyundai/deals-incentives/",
        confidence_score=0.85,
    ),
    # ===== FORD =====
    _program(
        "mfr-ford-lightning-cash",
        name="Ford F-150 Lightning $4,000 Cash Back",
        type="manufacturer",
        source_authority="Ford USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Ford",
            "models": ["F-150 Lightning"],
            "year": 2025,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=4000,
        incentive_max_amount=4000,
        start_date="2025-10-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://fordauthority.com/2026/01/ford-f-150-lightning-discount-lease-finance-deals-incentives-offers-january-2026/",
        confidence_score=0.8,
    ),
    _program(
        "mfr-ford-mache-cash",
        name="Ford Mustang Mach-E $4,000 Cash Back",
        type="manufacturer",
        source_authority="Ford USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Ford",
            "models": ["Mustang Mach-E"],
            "year": 2025,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=4000,
        incentive_max_amount=4000,
        start_date="2025-10-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.edmunds.com/ford/mustang-mach-e/2025/deals/",
        confidence_score=0.8,
    ),
    _program(
        "mfr-ford-mache-0apr",
        name="Ford Mustang Mach-E 0% APR for 72 months",
        type="manufacturer",
        source_authority="Ford USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Ford",
            "models": ["Mustang Mach-E"],
            "year": 2025,
            "new_or_used": "new",
        },
        buyer_criteria={"captive_financing": "Ford Credit"},
        incentive_value_type="rate_reduction",
        incentive_percentage=0,
        start_date="2025-10-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.edmunds.com/ford/mustang-mach-e/2025/deals/",
        confidence_score=0.8,
    ),
    # ===== CHEVY EV =====
    _program(
        "mfr-chevy-equinox-ev-cash",
        name="Chevrolet Equinox EV $8,750 Cash Bonus",
        type="manufacturer",
        source_authority="General Motors",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Chevrolet",
            "models": ["Equinox EV"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=8750,
        incentive_max_amount=8750,
        start_date="2026-01-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.kbb.com/chevrolet/deals-incentives/",
        confidence_score=0.85,
    ),
    _program(
        "mfr-chevy-equinox-ev-0apr",
        name="Chevrolet Equinox EV 0% APR for 60 months",
        type="manufacturer",
        source_authority="General Motors",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Chevrolet",
            "models": ["Equinox EV"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={"captive_financing": "GM Financial"},
        incentive_value_type="rate_reduction",
        incentive_percentage=0,
        start_date="2026-01-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.kbb.com/chevrolet/deals-incentives/",
        confidence_score=0.85,
    ),
    _program(
        "mfr-chevy-blazer-ev-cash",
        name="Chevrolet Blazer EV $3,500 Customer Cash",
        type="manufacturer",
        source_authority="General Motors",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Chevrolet",
            "models": ["Blazer EV"],
            "year": 2025,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=3500,
        incentive_max_amount=3500,
        start_date="2025-10-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.carsdirect.com/deals-articles/best-chevy-deals-special-offers",
        confidence_score=0.8,
    ),
    # ===== KIA =====
    _program(
        "mfr-kia-ev9-cash",
        name="Kia EV9 $10,000 Cash Back",
        type="manufacturer",
        source_authority="Kia America",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Kia",
            "models": ["EV9"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=10000,
        incentive_max_amount=10000,
        start_date="2026-01-01",
        end_date="2026-03-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.kbb.com/kia/ev9/deals-incentives/",
        confidence_score=0.85,
    ),
    # ===== VOLKSWAGEN =====
    _program(
        "mfr-vw-id4-bonus",
        name="Volkswagen ID.4 $7,500 Customer Bonus",
        type="manufacturer",
        source_authority="Volkswagen USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Volkswagen",
            "models": ["ID.4"],
            "year": 2025,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=7500,
        incentive_max_amount=7500,
        start_date="2025-10-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.kbb.com/volkswagen/id4/deals-incentives/",
        confidence_score=0.85,
    ),
    _program(
        "mfr-vw-idbuzz-bonus",
        name="Volkswagen ID.Buzz $7,500 Customer Bonus",
        type="manufacturer",
        source_authority="Volkswagen USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Volkswagen",
            "models": ["ID.Buzz"],
            "year": 2025,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=7500,
        incentive_max_amount=12500,
        start_date="2025-10-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.edmunds.com/volkswagen/id-buzz/2025/deals/",
        confidence_score=0.85,
    ),
    # ===== HONDA =====
    _program(
        "mfr-honda-prologue-sales-credit",
        name="Honda Prologue $8,000 Sales Credit",
        type="manufacturer",
        source_authority="Honda USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Honda",
            "models": ["Prologue"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=8000,
        incentive_max_amount=8000,
        start_date="2026-01-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.honda.com/prologue",
        confidence_score=0.9,
    ),
    _program(
        "mfr-honda-prologue-lease",
        name="Honda Prologue Lease Special $259/mo",
        type="manufacturer",
        source_authority="Honda USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Honda",
            "models": ["Prologue"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=259,
        incentive_max_amount=259,
        start_date="2026-01-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="lease_reduction",
        source_url="https://www.honda.com/prologue",
        confidence_score=0.9,
    ),
    # ===== POLESTAR =====
    _program(
        "mfr-polestar-4-sales-credit",
        name="Polestar 4 $10,000 Sales Credit",
        type="manufacturer",
        source_authority="Polestar USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Polestar",
            "models": ["Polestar 4"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=10000,
        incentive_max_amount=10000,
        start_date="2026-01-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.polestar.com/us/offers/new/?model=Polestar+4",
        confidence_score=0.9,
    ),
    _program(
        "mfr-polestar-3-sales-credit",
        name="Polestar 3 $5,000 Sales Credit",
        type="manufacturer",
        source_authority="Polestar USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Polestar",
            "models": ["Polestar 3"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=5000,
        incentive_max_amount=5000,
        start_date="2026-01-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.polestar.com/us/offers/new/?model=Polestar+3",
        confidence_score=0.9,
    ),
    _program(
        "mfr-polestar-2-sales-credit",
        name="Polestar 2 $8,000 Sales Credit",
        type="manufacturer",
        source_authority="Polestar USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Polestar",
            "models": ["Polestar 2"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=8000,
        incentive_max_amount=8000,
        start_date="2026-01-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.polestar.com/us/offers/new/?model=Polestar+2",
        confidence_score=0.9,
    ),
    # ===== LUCID =====
    _program(
        "mfr-lucid-air-savings",
        name="Lucid Air up to $13,750 Savings",
        type="manufacturer",
        source_authority="Lucid Motors",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Lucid",
            "models": ["Air"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=13750,
        incentive_max_amount=13750,
        start_date="2026-01-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.lucidmotors.com/offers",
        confidence_score=0.85,
    ),
    # ===== RIVIAN =====
    _program(
        "mfr-rivian-referral",
        name="Rivian $1,000 Referral Credit",
        type="manufacturer",
        source_authority="Rivian",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Rivian",
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=1000,
        start_date="2026-01-01",
        end_date="2026-12-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://rivian.com/configurations",
        confidence_score=0.85,
    ),
    # ===== OTHER MANUFACTURER 0% APR =====
    _program(
        "mfr-vw-0apr-atlas",
        name="Volkswagen Atlas 0% APR 60 months",
        type="manufacturer",
        source_authority="Volkswagen USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Volkswagen",
            "models": ["Atlas"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={"captive_financing": "VW Credit"},
        incentive_value_type="rate_reduction",
        incentive_percentage=0,
        start_date="2025-12-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.vw.com/en/models/atlas/builder",
        confidence_score=0.8,
    ),
    _program(
        "mfr-nissan-0apr-murano",
        name="Nissan Murano 0% APR 60 months",
        type="manufacturer",
        source_authority="Nissan USA",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Nissan",
            "models": ["Murano"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={"captive_financing": "Nissan Motor Acceptance Corporation"},
        incentive_value_type="rate_reduction",
        incentive_percentage=0,
        start_date="2025-12-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.nissanusa.com/shopping-tools/current-offers",
        confidence_score=0.8,
    ),
    _program(
        "mfr-tesla-0apr-modely",
        name="Tesla Model Y 0% APR 72 months",
        type="manufacturer",
        source_authority="Tesla",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Tesla",
            "models": ["Model Y"],
            "year": 2026,
            "new_or_used": "new",
        },
        buyer_criteria={"captive_financing": "Tesla Financing"},
        incentive_value_type="rate_reduction",
        incentive_percentage=0,
        start_date="2025-12-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.tesla.com/modely",
        confidence_score=0.8,
    ),
    # --- Cash Rebates ---
    _program(
        "mfr-stellantis-charger-daytona",
        name="Dodge Charger Daytona Cash Rebate",
        type="manufacturer",
        source_authority="Stellantis",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Dodge",
            "models": ["Charger Daytona"],
            "year": 2025,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=12750,
        incentive_max_amount=12750,
        start_date="2025-06-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.dodge.com/incentives.html",
        confidence_score=0.8,
    ),
    _program(
        "mfr-stellantis-ram1500",
        name="RAM 1500 Cash Rebate",
        type="manufacturer",
        source_authority="Stellantis",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Ram",
            "models": ["1500"],
            "year": 2025,
            "new_or_used": "new",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=11000,
        incentive_max_amount=11000,
        start_date="2025-06-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.ramtrucks.com/incentives.html",
        confidence_score=0.8,
    ),
    # --- Loyalty Programs ---
    _program(
        "mfr-gm-loyalty",
        name="GM/Chevrolet Loyalty Bonus",
        type="manufacturer",
        source_authority="General Motors",
        geographic_scope="national",
        vehicle_criteria={
            "make": ["Chevrolet", "GMC", "Buick", "Cadillac"],
            "new_or_used": "new",
        },
        buyer_criteria={
            "loyalty_type": "same_brand_or_cross_brand",
            "proof_required": "registration_or_lease",
        },
        incentive_value_type="fixed",
        incentive_amount=1500,
        incentive_max_amount=2500,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.chevrolet.com/current-offers",
        confidence_score=0.7,
    ),
    _program(
        "mfr-acura-loyalty",
        name="Acura Loyalty Bonus",
        type="manufacturer",
        source_authority="Acura",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Acura",
            "new_or_used": "new",
        },
        buyer_criteria={
            "loyalty_type": "same_brand",
            "proof_required": "registration_or_lease",
        },
        incentive_value_type="fixed",
        incentive_amount=2000,
        incentive_max_amount=2000,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.acura.com/special-offers",
        confidence_score=0.7,
    ),
    # --- Conquest Programs ---
    _program(
        "mfr-acura-conquest",
        name="Acura Conquest Bonus",
        type="manufacturer",
        source_authority="Acura",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Acura",
            "new_or_used": "new",
        },
        buyer_criteria={
            "conquest_type": "switching_from_competitor",
            "proof_required": "registration_or_lease",
        },
        incentive_value_type="fixed",
        incentive_amount=2000,
        incentive_max_amount=2000,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.acura.com/special-offers",
        confidence_score=0.7,
    ),
    _program(
        "mfr-mitsubishi-conquest",
        name="Mitsubishi Conquest Bonus",
        type="manufacturer",
        source_authority="Mitsubishi Motors",
        geographic_scope="national",
        vehicle_criteria={
            "make": "Mitsubishi",
            "new_or_used": "new",
        },
        buyer_criteria={
            "conquest_type": "switching_from_competitor",
            "proof_required": "registration_or_lease",
        },
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=1000,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.mitsubishicars.com/offers",
        confidence_score=0.7,
    ),
    _program(
        "mfr-anti-tesla-conquest",
        name="Anti-Tesla Conquest Offers (Various OEMs)",
        type="manufacturer",
        source_authority="Various",
        geographic_scope="national",
        vehicle_criteria={"new_or_used": "new"},
        buyer_criteria={
            "conquest_type": "switching_from_tesla",
            "proof_required": "registration_or_lease",
        },
        incentive_value_type="fixed",
        incentive_amount=5000,
        incentive_max_amount=17500,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.edmunds.com/car-incentives/",
        confidence_score=0.6,
    ),
]

# ============================================================================
# AFFINITY DISCOUNTS
# ============================================================================

AFFINITY = [
    _program(
        "aff-toyota-military",
        name="Toyota Military Discount",
        type="affinity",
        source_authority="Toyota USA",
        geographic_scope="national",
        vehicle_criteria={"make": "Toyota", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "military", "captive_financing": "Toyota Financial Services"},
        incentive_value_type="fixed",
        incentive_amount=500,
        incentive_max_amount=500,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.toyota.com/military-rebate",
        confidence_score=0.9,
    ),
    _program(
        "aff-toyota-grad",
        name="Toyota College Grad Discount",
        type="affinity",
        source_authority="Toyota USA",
        geographic_scope="national",
        vehicle_criteria={"make": "Toyota", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "college_grad", "captive_financing": "Toyota Financial Services"},
        incentive_value_type="fixed",
        incentive_amount=500,
        incentive_max_amount=500,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.toyota.com/college-grad-rebate",
        confidence_score=0.9,
    ),
    _program(
        "aff-honda-military",
        name="Honda Military Discount",
        type="affinity",
        source_authority="Honda USA",
        geographic_scope="national",
        vehicle_criteria={"make": "Honda", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "military", "captive_financing": "Honda Financial Services"},
        incentive_value_type="fixed",
        incentive_amount=500,
        incentive_max_amount=500,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.honda.com/military-appreciation-offer",
        confidence_score=0.9,
    ),
    _program(
        "aff-honda-grad",
        name="Honda College Grad Discount",
        type="affinity",
        source_authority="Honda USA",
        geographic_scope="national",
        vehicle_criteria={"make": "Honda", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "college_grad", "captive_financing": "Honda Financial Services"},
        incentive_value_type="fixed",
        incentive_amount=500,
        incentive_max_amount=500,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.honda.com/college-graduate-offer",
        confidence_score=0.9,
    ),
    _program(
        "aff-ford-military",
        name="Ford Military & Veterans Bonus Cash",
        type="affinity",
        source_authority="Ford USA",
        geographic_scope="national",
        vehicle_criteria={"make": "Ford", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "military"},
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=1000,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.ford.com/support/service-members/",
        confidence_score=0.9,
    ),
    _program(
        "aff-ford-responder",
        name="Ford First Responder Bonus Cash",
        type="affinity",
        source_authority="Ford USA",
        geographic_scope="national",
        vehicle_criteria={"make": "Ford", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "first_responder"},
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=1000,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.ford.com/support/first-responders/",
        confidence_score=0.9,
    ),
    _program(
        "aff-ford-educator",
        name="Ford Educator Discount",
        type="affinity",
        source_authority="Ford USA",
        geographic_scope="national",
        vehicle_criteria={"make": "Ford", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "educator"},
        incentive_value_type="fixed",
        incentive_amount=500,
        incentive_max_amount=500,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.ford.com/support/educators/",
        confidence_score=0.9,
    ),
    _program(
        "aff-gm-military",
        name="GM Military Discount",
        type="affinity",
        source_authority="General Motors",
        geographic_scope="national",
        vehicle_criteria={"make": ["Chevrolet", "GMC", "Buick", "Cadillac"], "new_or_used": "new"},
        buyer_criteria={"affinity_group": "military"},
        incentive_value_type="fixed",
        incentive_amount=750,
        incentive_max_amount=750,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.chevrolet.com/current-offers",
        confidence_score=0.9,
    ),
    _program(
        "aff-hyundai-military",
        name="Hyundai Military Appreciation Discount",
        type="affinity",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={"make": "Hyundai", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "military"},
        incentive_value_type="fixed",
        incentive_amount=500,
        incentive_max_amount=500,
        start_date="2026-01-07",
        end_date="2026-12-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.hyundaiusa.com/us/en/special-programs",
        confidence_score=0.9,
    ),
    _program(
        "aff-hyundai-responder",
        name="Hyundai First Responder Discount",
        type="affinity",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={"make": "Hyundai", "new_or_used": "new"},
        buyer_criteria={
            "affinity_group": "first_responder",
            "note": "Police, Sheriffs, Correctional Officers, State Troopers, Firefighters, EMT/Paramedics, 911 Dispatchers and spouses",
        },
        incentive_value_type="fixed",
        incentive_amount=500,
        incentive_max_amount=500,
        start_date="2026-01-07",
        end_date="2026-12-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.hyundaiusa.com/us/en/special-programs/first-responders",
        confidence_score=0.9,
    ),
    _program(
        "aff-hyundai-college-grad",
        name="Hyundai College Graduate Bonus ($400)",
        type="affinity",
        source_authority="Hyundai USA",
        geographic_scope="national",
        vehicle_criteria={"make": "Hyundai", "new_or_used": "new"},
        buyer_criteria={
            "affinity_group": "college_grad",
            "captive_financing": "Hyundai Motor Finance",
            "note": "Graduated within past 2 years or graduating within 6 months",
        },
        incentive_value_type="fixed",
        incentive_amount=400,
        incentive_max_amount=400,
        start_date="2026-01-01",
        end_date="2026-12-31",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.hyundaiusa.com/us/en/special-programs/college-grad",
        confidence_score=0.9,
    ),
    _program(
        "aff-kia-military",
        name="Kia Military Discount",
        type="affinity",
        source_authority="Kia America",
        geographic_scope="national",
        vehicle_criteria={"make": "Kia", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "military"},
        incentive_value_type="fixed",
        incentive_amount=500,
        incentive_max_amount=1500,
        start_date="2026-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.kia.com/us/en/special-offers",
        confidence_score=0.8,
    ),
    _program(
        "aff-tesla-military",
        name="Tesla Military Discount",
        type="affinity",
        source_authority="Tesla",
        geographic_scope="national",
        vehicle_criteria={"make": "Tesla", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "military"},
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=1000,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.tesla.com",
        confidence_score=0.8,
    ),
    _program(
        "aff-tesla-student",
        name="Tesla Student Discount",
        type="affinity",
        source_authority="Tesla",
        geographic_scope="national",
        vehicle_criteria={"make": "Tesla", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "college_grad"},
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=1000,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.tesla.com",
        confidence_score=0.8,
    ),
    _program(
        "aff-tesla-responder",
        name="Tesla First Responder Discount",
        type="affinity",
        source_authority="Tesla",
        geographic_scope="national",
        vehicle_criteria={"make": "Tesla", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "first_responder"},
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=1000,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.tesla.com",
        confidence_score=0.8,
    ),
    _program(
        "aff-tesla-educator",
        name="Tesla Educator Discount",
        type="affinity",
        source_authority="Tesla",
        geographic_scope="national",
        vehicle_criteria={"make": "Tesla", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "educator"},
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=1000,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.tesla.com",
        confidence_score=0.8,
    ),
    _program(
        "aff-tesla-healthcare",
        name="Tesla Healthcare Worker Discount",
        type="affinity",
        source_authority="Tesla",
        geographic_scope="national",
        vehicle_criteria={"make": "Tesla", "new_or_used": "new"},
        buyer_criteria={"affinity_group": "healthcare"},
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=1000,
        start_date="2025-01-01",
        funding_status="open",
        claim_mechanism="point_of_sale",
        source_url="https://www.tesla.com",
        confidence_score=0.8,
    ),
]

# ============================================================================
# UTILITY INCENTIVES
# ============================================================================

UTILITY = [
    _program(
        "util-pge-charger",
        name="PG&E Charger Rebate",
        type="utility",
        source_authority="Pacific Gas & Electric",
        geographic_scope="utility_territory",
        eligible_states=["CA"],
        vehicle_criteria={"category": "charger_installation"},
        buyer_criteria={"income_eligible": True},
        incentive_value_type="fixed",
        incentive_amount=700,
        incentive_max_amount=700,
        start_date="2024-01-01",
        funding_status="open",
        claim_mechanism="post_purchase_rebate",
        source_url="https://www.pge.com/en/clean-energy/electric-vehicles.html",
        confidence_score=0.8,
    ),
    _program(
        "util-pge-ev-rebate",
        name="PG&E Pre-Owned EV Rebate",
        type="utility",
        source_authority="Pacific Gas & Electric",
        geographic_scope="utility_territory",
        eligible_states=["CA"],
        vehicle_criteria={
            "fuel_types": ["BEV"],
            "new_or_used": "used",
        },
        buyer_criteria={"income_eligible": True},
        incentive_value_type="fixed",
        incentive_amount=4000,
        incentive_max_amount=4000,
        start_date="2024-01-01",
        funding_status="open",
        claim_mechanism="post_purchase_rebate",
        source_url="https://www.pge.com/en/clean-energy/electric-vehicles.html",
        confidence_score=0.8,
    ),
    _program(
        "util-sce-ev-rebate",
        name="SCE Pre-Owned EV Rebate",
        type="utility",
        source_authority="Southern California Edison",
        geographic_scope="utility_territory",
        eligible_states=["CA"],
        vehicle_criteria={
            "fuel_types": ["BEV"],
            "new_or_used": "used",
        },
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=4000,
        start_date="2024-01-01",
        funding_status="open",
        claim_mechanism="post_purchase_rebate",
        source_url="https://www.sce.com/residential/electric-vehicles",
        confidence_score=0.8,
    ),
    _program(
        "util-sce-charger",
        name="SCE Level 2 Charger Install Rebate",
        type="utility",
        source_authority="Southern California Edison",
        geographic_scope="utility_territory",
        eligible_states=["CA"],
        vehicle_criteria={"category": "charger_installation"},
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=4200,
        incentive_max_amount=4200,
        start_date="2024-01-01",
        end_date="2026-06-30",
        funding_status="open",
        claim_mechanism="post_purchase_rebate",
        source_url="https://www.sce.com/residential/electric-vehicles",
        confidence_score=0.8,
    ),
    _program(
        "util-sdge-ev-plan",
        name="SDG&E EV Pricing Plan (reduced electricity rate)",
        type="utility",
        source_authority="San Diego Gas & Electric",
        geographic_scope="utility_territory",
        eligible_states=["CA"],
        vehicle_criteria={"fuel_types": ["BEV", "PHEV"]},
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=500,
        incentive_max_amount=500,
        start_date="2024-01-01",
        funding_status="open",
        claim_mechanism="post_purchase_rebate",
        source_url="https://www.sdge.com/residential/electric-vehicles",
        confidence_score=0.7,
    ),
    _program(
        "util-comed-charger",
        name="ComEd Level 2 Charger Install Rebate",
        type="utility",
        source_authority="Commonwealth Edison",
        geographic_scope="utility_territory",
        eligible_states=["IL"],
        vehicle_criteria={"category": "charger_installation"},
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=2500,
        start_date="2026-01-01",
        funding_status="open",
        claim_mechanism="post_purchase_rebate",
        source_url="https://www.comed.com/SmartEnergy/InnovativeTechnologies/Pages/ElectricVehicles.aspx",
        confidence_score=0.8,
    ),
    _program(
        "util-eversource-charger",
        name="Eversource Home Charger Rebate",
        type="utility",
        source_authority="Eversource Energy",
        geographic_scope="utility_territory",
        eligible_states=["CT"],
        vehicle_criteria={"category": "charger_installation"},
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=1000,
        incentive_max_amount=1000,
        start_date="2024-01-01",
        funding_status="open",
        claim_mechanism="post_purchase_rebate",
        source_url="https://www.eversource.com/content/residential/save-money-energy/clean-energy-options/electric-vehicles",
        confidence_score=0.8,
    ),
    _program(
        "util-ngrid-wiring",
        name="National Grid Wiring Upgrade Rebate",
        type="utility",
        source_authority="National Grid",
        geographic_scope="utility_territory",
        eligible_states=["MA"],
        vehicle_criteria={"category": "charger_installation"},
        buyer_criteria={},
        incentive_value_type="fixed",
        incentive_amount=700,
        incentive_max_amount=700,
        start_date="2024-01-01",
        funding_status="open",
        claim_mechanism="post_purchase_rebate",
        source_url="https://www.nationalgridus.com/MA-Home/Energy-Saving-Programs/Electric-Vehicle-Charging",
        confidence_score=0.8,
    ),
]

# ============================================================================
# ALL PROGRAMS
# ============================================================================

ALL_PROGRAMS = FEDERAL + STATE + MANUFACTURER + AFFINITY + UTILITY

# ============================================================================
# STACKING RULES
# After all programs are defined, set up mutual exclusion relationships.
# Cash rebates and 0% APR from the same manufacturer are mutually exclusive.
# ============================================================================


def _apply_stacking_rules(programs: list[dict]) -> None:
    """
    Mark mutual exclusion between 0% APR and cash rebates for each OEM.
    State + manufacturer + utility + affinity are all stackable (default).
    30C charger credit is stackable with all vehicle incentives (default).
    """
    apr_ids = {
        "Stellantis": [],
        "Hyundai USA": [],
        "Hyundai": [],
        "Volkswagen USA": [],
        "Volkswagen": [],
        "Nissan USA": [],
        "Nissan": [],
        "Tesla": [],
        "General Motors": [],
        "Toyota USA": [],
    }
    cash_ids = {
        "Stellantis": [],
        "Hyundai USA": [],
        "Hyundai": [],
        "Volkswagen USA": [],
        "Volkswagen": [],
        "Nissan USA": [],
        "Nissan": [],
        "Tesla": [],
        "General Motors": [],
        "Toyota USA": [],
    }

    for p in programs:
        authority = p["source_authority"]
        if p["incentive_value_type"] == "rate_reduction" and authority in apr_ids:
            apr_ids[authority].append(p["id"])
        elif (
            p["type"] == "manufacturer"
            and p["incentive_value_type"] == "fixed"
            and authority in cash_ids
        ):
            cash_ids[authority].append(p["id"])

    by_id = {p["id"]: p for p in programs}
    for authority in apr_ids:
        for apr_id in apr_ids[authority]:
            for cash_id in cash_ids.get(authority, []):
                by_id[apr_id]["mutually_exclusive_with"].append(cash_id)
                by_id[cash_id]["mutually_exclusive_with"].append(apr_id)


_apply_stacking_rules(ALL_PROGRAMS)


# ============================================================================
# DB INSERTION
# ============================================================================


async def seed(database_url: str | None = None) -> None:
    url = database_url or DATABASE_URL
    engine = create_async_engine(url, echo=False)
    session_factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with session_factory() as session:
        # Upsert each program (idempotent via ON CONFLICT)
        for p in ALL_PROGRAMS:
            await session.execute(
                text("""
                    INSERT INTO incentive_programs (
                        id, name, type, source_authority, geographic_scope,
                        eligible_states, eligible_zips,
                        vehicle_criteria, buyer_criteria,
                        incentive_value_type, incentive_amount, incentive_max_amount, incentive_percentage,
                        stackable_with, mutually_exclusive_with,
                        start_date, end_date, application_deadline,
                        funding_status, claim_mechanism,
                        last_verified, source_url, confidence_score,
                        is_active, created_at, updated_at
                    ) VALUES (
                        :id, :name, :type, :source_authority, :geographic_scope,
                        :eligible_states, :eligible_zips,
                        :vehicle_criteria, :buyer_criteria,
                        :incentive_value_type, :incentive_amount, :incentive_max_amount, :incentive_percentage,
                        :stackable_with, :mutually_exclusive_with,
                        :start_date, :end_date, :application_deadline,
                        :funding_status, :claim_mechanism,
                        :last_verified, :source_url, :confidence_score,
                        :is_active, :created_at, :updated_at
                    )
                    ON CONFLICT (id) DO UPDATE SET
                        name = EXCLUDED.name,
                        type = EXCLUDED.type,
                        source_authority = EXCLUDED.source_authority,
                        geographic_scope = EXCLUDED.geographic_scope,
                        eligible_states = EXCLUDED.eligible_states,
                        eligible_zips = EXCLUDED.eligible_zips,
                        vehicle_criteria = EXCLUDED.vehicle_criteria,
                        buyer_criteria = EXCLUDED.buyer_criteria,
                        incentive_value_type = EXCLUDED.incentive_value_type,
                        incentive_amount = EXCLUDED.incentive_amount,
                        incentive_max_amount = EXCLUDED.incentive_max_amount,
                        incentive_percentage = EXCLUDED.incentive_percentage,
                        stackable_with = EXCLUDED.stackable_with,
                        mutually_exclusive_with = EXCLUDED.mutually_exclusive_with,
                        start_date = EXCLUDED.start_date,
                        end_date = EXCLUDED.end_date,
                        application_deadline = EXCLUDED.application_deadline,
                        funding_status = EXCLUDED.funding_status,
                        claim_mechanism = EXCLUDED.claim_mechanism,
                        last_verified = EXCLUDED.last_verified,
                        source_url = EXCLUDED.source_url,
                        confidence_score = EXCLUDED.confidence_score,
                        is_active = EXCLUDED.is_active,
                        updated_at = EXCLUDED.updated_at
                """),
                {
                    "id": str(p["id"]),
                    "name": p["name"],
                    "type": p["type"],
                    "source_authority": p["source_authority"],
                    "geographic_scope": p["geographic_scope"],
                    "eligible_states": p["eligible_states"],
                    "eligible_zips": p["eligible_zips"],
                    "vehicle_criteria": json.dumps(p["vehicle_criteria"]),
                    "buyer_criteria": json.dumps(p["buyer_criteria"]),
                    "incentive_value_type": p["incentive_value_type"],
                    "incentive_amount": p["incentive_amount"],
                    "incentive_max_amount": p["incentive_max_amount"],
                    "incentive_percentage": p["incentive_percentage"],
                    "stackable_with": [str(x) for x in p["stackable_with"]],
                    "mutually_exclusive_with": [str(x) for x in p["mutually_exclusive_with"]],
                    "start_date": p["start_date"],
                    "end_date": p["end_date"],
                    "application_deadline": p["application_deadline"],
                    "funding_status": p["funding_status"],
                    "claim_mechanism": p["claim_mechanism"],
                    "last_verified": p["last_verified"],
                    "source_url": p["source_url"],
                    "confidence_score": p["confidence_score"],
                    "is_active": p["is_active"],
                    "created_at": p["created_at"],
                    "updated_at": p["updated_at"],
                },
            )

        await session.commit()

    await engine.dispose()
    print(f"Seeded {len(ALL_PROGRAMS)} incentive programs.")


if __name__ == "__main__":
    asyncio.run(seed())
